---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  # require_chef_omnibus: 12.21.4
  attributes:
    icinga2:
      ignore_version: false
    apt:
      compile_time_update: true
      # temp fix
      disable_conf_d: false
      confd:
        install_recommends: false

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-18.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-20.04
    run_list:
      - recipe[apt::default]
  - name: debian-8.5
    run_list:
      - recipe[apt::default]
  - name: debian-9.5
    run_list:
      - recipe[apt::default]
  - name: debian-10
    run_list:
      - recipe[apt::default]


suites:
  - name: chef13server
    driver:
      require_chef_omnibus: 13.3.42
    verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
  - name: chef14server
    driver:
      require_chef_omnibus: 14
      verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
  - name: chef15server
    driver:
      require_chef_omnibus: 15
    verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
  - name: chef16server
    driver:
      require_chef_omnibus: 16
    verifier:
      inspec_tests:
        - test/smoke/server
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2-test::default]
