---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: server
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    run_list:
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]
    attributes:
      icinga2:
        version: '2.4.10-1'
        classic_ui:
          version: '2.4.10-1'

  - name: client
    run_list:
      - recipe[icinga2::client]
    attributes:
      icinga2:
        version: '2.4.10-1'
    
  - name: web2
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
    run_list:
      - recipe[icinga2::default]
      - recipe[icinga2::server]
      - recipe[icinga2-test::default]
    attributes:
     icinga2:
      version: '2.4.10-1'
      web2:
        enable: true
      classic_ui:
        enable: false
